### ISSUE TITLE
Doesn't handle Help when no module is given

### ISSUE THREAD

**Issue by happykhan** [zheminzhou/EToKi#6]
`python EToKi/EToKi.py -h
`
Doesn't handle Help when no module is given

```
Traceback (most recent call last):
  File "EToKi/EToKi.py", line 55, in <module>
    etoki()
  File "EToKi/EToKi.py", line 31, in etoki
    exec('from modules.{0} import {0}'.format(sys.argv[1]))
  File "<string>", line 1
    from modules.-h import -h
```

**Comment by zheminzhou** [comment]
Thanks. Fixed in the latest update.
